dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0  # Эта библиотека позволит Flutter "общаться" с вашим Node.js
dependencies:
  flutter:
    sdk: flutter
  record: ^5.1.0        # Ses ýazmak üçin
  path_provider: ^2.1.2 # Faýly saklamak üçin
  http: ^1.2.0          # Backend-e ugratmak üçin
